
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Promise</title>
  </head>
  <body>
    <button id="btn">Click me</button>

    <script>
      const soz1 = () => {
        return new Promise((resolve) => {
          setTimeout(() => {
            resolve("Sözüm söz 1");
          }, 2000);
        });
      };

      const soz2 = () => {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            resolve("Sözüm söz 2");
            //reject("HAta oluştu")
          }, 1000);
        });
      };

      const soz3 = () => {
        return new Promise((resolve) => {
          setTimeout(() => {
            resolve("Sözüm söz 3");
          }, 4000);
        });
      };

      const soz4 = () => {
        return new Promise((resolve) => {
          setTimeout(() => {
            resolve("Sözüm söz 4");
          }, 500);
        });
      };
    
    
      document.getElementById("btn").addEventListener("click", async ()=>{
        console.log("Awating...");

        try {
          const resp1 = await soz1();
          console.log(resp1);

          const resp2 = await soz2();
          console.log(resp2);

          const resp3 = await soz3();
          console.log(resp3);

          const resp4 = await soz4();
          console.log(resp4);
       
          // promise lerden dönen reject durumlarını catch yakalar
        } catch (error) {
          console.log(error);
        }
        finally{

        }

        /*
        FETCH komutunun senkron kullanımı
        
        const resp = await fetch("http://localhost/api/users");
        const data = await resp.json();

        */
       
        console.log("Hello");

      })



    
    
    </script>
  </body>
</html>